query {
  repository(owner: $OWNER, name: $NAME) {
    pullRequests(last:$COUNT, before:$BEFORE, states:MERGED) {
      nodes {
        number
        createdAt
        author {
          ... on Node {
            id
          }
          ... on User {
            databaseId
          }
          ... on Actor {
            login
          }
        }
        mergedAt
        mergedBy {
          ... on Node {
            id
          }
          ... on User {
            databaseId
          }
          ... on Actor {
            login
          }
        }
        commits {
          totalCount
        }
      }
      pageInfo {
        startCursor
        endCursor
      }
    }
  }
}
